name: DEV Branch Versioning
on:
  pull_request:
    branches: [dev]
    types:
      - closed

jobs:
  build:
    name: Create Release  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Taking the Latest Release Tag number
        id: releaseVersion
        run: |
          TargetBranch=${{ github.ref }}
          echo "Target Branch: $TargetBranch"
          RepoInfo=${{ github.repository }}
          echo "Repo Info: $RepoInfo"
          TargetRepo=$( echo "$RepoInfo" | cut -d "/" -f 2 )
          echo "Target Repo: $TargetRepo "
          TargetOwner=$( echo "$RepoInfo" | cut -d "/" -f 1 )
          echo "Target Owner: $TargetOwner"
          release_json=$(curl https://api.github.com/repos/$TargetOwner/$TargetRepo/tags)
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          if [[ "$Release_tag" == *"."* ]]; then
            echo "$TargetBranch branch tag found"
            echo "Release_tag: Latest Tag is : $Release_tag"
          else
            echo "$TargetBranch branch tag NOT found"
            Release_tag=$(echo "1.0.0")
            echo "Release_tag: Latest Tag is : $Release_tag"
          fi
          echo ::set-output name=Release_tag::"$Release_tag"
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Bumping Major Index
        id: bump_version_major
        if: contains(github.event.pull_request.title, 'major')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.releaseVersion.outputs.Release_tag }}
          version-fragment: 'major'
                    
      - name: Bumping Minor Index
        id: bump_version_minor
        if: contains(github.event.pull_request.title, 'minor')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.releaseVersion.outputs.Release_tag }}
          version-fragment: 'feature'
          
      - name: Bumping Patch Index 
        id: bump_version_patch
        if: contains(github.event.pull_request.title, 'patch')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.releaseVersion.outputs.Release_tag }}
          version-fragment: 'bug'
          
      - name: Create release version for bump_version_major
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #owner="Brotherh1"
          #repo="Personal"
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/$TargetOwner/$TargetRepo/tags \
            -d '{"tag_name":"${{ steps.bump_version_major.outputs.next-version }}","target_commitish":"$TargetBranch","name":"${{ steps.bump_version_major.outputs.next-version }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/$TargetOwner/$TargetRepo/tags \
            -d '{"tag_name":"${{ steps.bump_version_minor.outputs.next-version }}","target_commitish":"$TargetBranch","name":"${{ steps.bump_version_minor.outputs.next-version }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/$TargetOwner/$TargetRepo/tags \
            -d '{"tag_name":"${{ steps.bump_version_patch.outputs.next-version }}","target_commitish":"$TargetBranch","name":"${{ steps.bump_version_patch.outputs.next-version }}","body":"Description of the release - Patch $TargetBranch","draft":false,"prerelease":false,"generate_release_notes":false}'
